### ISSUE TITLE
Go() hangs if you only check for errors

### ISSUE THREAD

**Issue by tarrant** [afex/hystrix-go#7]
Given the following code hystrix will permanently hang a go routine:

```go
errors := hystrix.Go("foo", func() error {
       fmt.Println("Just checking if success/failure")
	return nil
}, nil)

err := <- errors
return err
```

**Comment by afex** [comment]
this is identical to 

```
errors := make(chan error)
go func() {
  // don't push anything to errors
}
err := <-errors
return err
```

it is a programming error and not a hystrix problem. 

closing.

**Comment by tarrant** [comment]
I disagree. `hystrix.Go` should close the channel when it is finished. Signaling that it is done.

**Comment by afex** [comment]
good point. i'll close the channel when the command is done
